### ISSUE TITLE
Integrate Third-Party Audio Channel

### ISSUE THREAD

**Issue by moconnell9** [b6938236/high-quality-chat#12]
## Story / Task Details

- [ ] ~~Enable sending and compression low quality audio to server~~
- [ ] ~~Enable receiving of low quality audio from server~~
- [X] Enable playback of low quality audio on local machine

## Acceptance Scenarios

Given: user joins session
When: user turns on 'mic' icon
Then: user's audio stream is compressed, sent, and played to all other parties

Given: third party user gives one-click permission to be recorded
When: producer scrubs back in time
Then: producer can listen to and save low quality input from third parties

## Done Done Criteria

Tests passed and merged into master

----------------

User story reference: Receive feedback from interested parties so I can re-record immediately

**Comment by b6938236** [comment]
Voice quality audio streams are sent to server over SIP.  The main task in this issue is playing back sections recorded by the artist
