### ISSUE TITLE
Adding text chat to application

### ISSUE THREAD

**Issue by b6938236** [b6938236/high-quality-chat#64]
- [x] Have the GUI display text messages sent from chat
- [x] Have the GUI send text messages from chat
- [x] Get Connection details from settings (to be filled out by assignee)

Done: 

Given: Chat and GUI are hooked up and chat server is running
When: A user sends a message through the GUI
Then: Have all other clients display the message on the GUI

Done Done:

Tested and merged into master
