### ISSUE TITLE
Send high quality audio after recording

### ISSUE THREAD

**Issue by cptarnie** [b6938236/high-quality-chat#7]
## Story / Task Details
This is the backend
- [x] Download studio ready recordings
- [x] Send studio ready recordings
- [x] Cut studio quality audio files into arbitrary chunks

## Acceptance Scenarios
\- Given: artist participates in an audio recording
\- When: artist leaves the channel
\- Then: server receives the studio ready recording from artist

\- Given: artist participates in an audio recording
\- When: artist leaves the channel
\- Then: artist sends the server studio ready recordings

\- Given: voice communication is being received
\- When: producer hits a "mark out" button
\- Then: studio quality audio is cut into pieces

## Done Done Criteria

Tests passed and merged into master

---

User story reference: Send high quality audio quickly after recording so I can distribute files

**Comment by b6938236** [comment]
Changes in recording design now prevent having to cut studio quality files

**Comment by faizanv** [comment]
Added file transfer through websockets

**Comment by faizanv** [comment]
File transfer direct to producers
